# Generated by Django 4.2.4 on 2023-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelships',
            name='moment',
            field=models.DateTimeField(null=True),
        ),
    ]
